# Generated by Django 3.0 on 2020-12-12 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_desc', models.CharField(choices=[('Packed', 'Packed'), ('Shipped', 'Shipped'), ('In-Transit', 'In-Transit'), ('Out for delivery', 'Out for delivery')], default='Packed', max_length=300)),
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=5000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
