# Generated by Django 3.0 on 2020-12-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='username',
        ),
    ]
