# Generated by Django 3.0.3 on 2020-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('minprice', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
