# Generated by Django 3.0.8 on 2020-07-19 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 15, 1, 25, 819681)),
        ),
        migrations.AlterField(
            model_name='post',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 15, 1, 25, 819681)),
        ),
    ]
