# Generated by Django 3.0.8 on 2020-07-18 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200718_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 18, 34, 58, 359881)),
        ),
        migrations.AlterField(
            model_name='post',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 18, 34, 58, 359881)),
        ),
    ]
