# Generated by Django 3.0.8 on 2020-07-18 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200718_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 19, 8, 51, 395165)),
        ),
        migrations.AlterField(
            model_name='post',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 19, 8, 51, 395165)),
        ),
    ]
