# Generated by Django 3.0.7 on 2020-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200702_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
