# Generated by Django 3.0.7 on 2020-07-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='current_bid',
        ),
    ]
