# Generated by Django 3.0.5 on 2020-07-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
