# Generated by Django 3.0.8 on 2020-07-16 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
