# Generated by Django 3.0.5 on 2020-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200716_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
