# Generated by Django 3.0.3 on 2020-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200313_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='kertna', max_length=300),
        ),
    ]
