# Generated by Django 3.0.5 on 2020-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200314_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='username', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Paintings', 'Paintings'), ('Historic', 'Historic'), ('Others', 'Others')], max_length=300),
        ),
    ]
