# Generated by Django 3.0 on 2020-12-11 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank='True', upload_to='items/')),
                ('category', models.CharField(choices=[('Musical Instruments', 'Musical Instruments'), ('Photography', 'Photography'), ('Dance', 'Dance'), ('Painting', 'Painting')], max_length=300)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermidiate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('organisation', models.CharField(max_length=300)),
                ('instructor', models.CharField(max_length=300)),
                ('noofweeks', models.IntegerField()),
                ('video1', models.FileField(blank='True', upload_to='items/')),
                ('d1', models.CharField(default='video1', max_length=1000)),
                ('video2', models.FileField(blank='True', upload_to='items/')),
                ('d2', models.CharField(default='video2', max_length=1000)),
                ('video3', models.FileField(blank='True', upload_to='items/')),
                ('d3', models.CharField(default='video3', max_length=1000)),
                ('video4', models.FileField(blank='True', upload_to='items/')),
                ('d4', models.CharField(default='video4', max_length=1000)),
                ('video5', models.FileField(blank='True', upload_to='items/')),
                ('d5', models.CharField(default='video5', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank='True', upload_to='items/')),
                ('category', models.CharField(choices=[('Bongodrum', 'Bongodrum'), ('Conga', 'Conga'), ('Doublebass', 'Doublebass'), ('Guitar', 'Guitar'), ('Piano', 'Piano'), ('Sitar', 'Sitar'), ('Snare_drum', 'Snare_drum'), ('Trumpet', 'Trumpet'), ('Violin', 'Violin')], max_length=300)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default1.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('c1', models.BooleanField(default=False)),
                ('c2', models.BooleanField(default=False)),
                ('c3', models.BooleanField(default=False)),
                ('c4', models.BooleanField(default=False)),
                ('c5', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('v1', models.BooleanField(default=False)),
                ('v2', models.BooleanField(default=False)),
                ('v3', models.BooleanField(default=False)),
                ('v4', models.BooleanField(default=False)),
                ('v5', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
