# Generated by Django 3.0 on 2020-12-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='About',
            field=models.CharField(default='Tell us about your self', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default='Add your Skills', max_length=1000),
        ),
    ]
