# Generated by Django 3.0 on 2020-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderupdate_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='logistics_name',
            field=models.CharField(default='ecart', max_length=5000),
            preserve_default=False,
        ),
    ]
